// Netlify Function: POST /api/insight
// Receives aggregated GitHub stats and returns a short, plain-English summary
// generated by Gemini (Google's free-tier LLM API). Keeps the API key server-side only.

export async function handler(event) {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: 'method not allowed' };
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return {
      statusCode: 500,
      body: JSON.stringify({ error: 'server missing GEMINI_API_KEY' }),
    };
  }

  let stats;
  try {
    stats = JSON.parse(event.body);
  } catch {
    return { statusCode: 400, body: JSON.stringify({ error: 'invalid JSON body' }) };
  }

  const { username, totals, languages, recentActivity } = stats;

  const prompt = `You're looking at GitHub activity stats for the user "${username}".

Totals: ${totals.repos} repos, ${totals.stars} stars earned, ${totals.forks} forks.
Top languages by repo count: ${languages.map((l) => `${l.name} (${l.value})`).join(', ') || 'none listed'}.
Recent activity (most recent first): ${
    recentActivity.map((e) => `${e.label} ${e.repo}`).join('; ') || 'none recent'
  }.

Write a 2-3 sentence, plain-English summary of this person's coding activity and focus.
Be specific and grounded only in the numbers given — don't invent details.
No preamble, just the summary.`;

  try {
    // gemini-flash-latest is a Google-maintained alias that always points at
    // their current recommended free-tier Flash model, so this keeps working
    // as Google ships new model versions without needing code changes.
    const res = await fetch(
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-goog-api-key': apiKey,
        },
        body: JSON.stringify({
          contents: [{ role: 'user', parts: [{ text: prompt }] }],
        }),
      }
    );

    if (!res.ok) {
      const errText = await res.text();
      console.error('Gemini API error:', res.status, errText);
      return {
        statusCode: 502,
        body: JSON.stringify({ error: 'upstream AI request failed' }),
      };
    }

    const data = await res.json();
    const insight =
      data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || 'no insight generated';

    return {
      statusCode: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ insight }),
    };
  } catch (err) {
    console.error('insight function error:', err);
    return { statusCode: 500, body: JSON.stringify({ error: 'internal error' }) };
  }
}
